delicious_username: "username"
delicious_password: "password"
server: "irc.barelylegalbovines.com"
channels:
    - "#test"
username: "yummy"
realname: "!help for information."
nicknames:
    - "yummy"
    - "tasty"
    - "delicious"
loud: true
daemonize: false
welcome_text: "I R HERE"
features:
    - "dbot/features/ping"
    - "dbot/features/delicious"
    - "dbot/features/help"
